Import("*")

import platform

mk8900image = henv.Program('mk8900image', ['mk8900image.c'], LIBPATH='/usr/X11/lib', LIBS=['m', 'dl', 'xpwn', 'png', 'crypto', 'z'])

def generate_actions(source, target, env, for_sig=False, **kw):
	Depends(target, mk8900image)

	if len(source) > 2:
		return "%s %s %s %s %s" % (str(mk8900image[0]), source[0], target[0], source[1], source[2])

	if len(source) > 1:
		return "%s %s %s %s" % (str(mk8900image[0]), source[0], target[0], source[1])
	
	return "%s %s %s" % (str(mk8900image[0]), source[0], target[0])

env.Append(BUILDERS = {'Make8900Image': Builder(generator=generate_actions)})
